[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
title = "Alacritty"
dynamic_title = false
[window.padding]
x = 8
y = 8

[font]
size = 11
[font.normal]
family = "Hack"
style = "Regular"

[colors.primary]
background = "#000000"
foreground = "#f9ecd4"
bright_foreground = "#ffeac3"
[colors.cursor]
text = "#000000"
cursor = "#ffeac3"
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.selection]
text = "CellForeground"
background = "#707070"
[colors.normal]
black = "#303030"
red = "#d9ad94"
green = "#c3d994"
yellow = "#d9b911"
blue = "#1185d9"
magenta = "#d911b9"
cyan = "#94d9b8"
white = "#e0e0e0"
[colors.bright]
black = "#606060"
red = "#ffcbae"
green = "#e5ffae"
yellow = "#ffd914"
blue = "#149cff"
magenta = "#ff14d9"
cyan = "#aeffd8"
white = "#ffffff"
[colors.search.matches]
foreground = "#707070"
background = "#c3d994"
[colors.search.focused_match]
foreground = "#707070"
background = "#ffc281"
[colors.footer_bar]
background = "#000000"
foreground = "#e0e0e0"
[colors.hints.start]
foreground = "#000000"
background = "#d9b911"
[colors.hints.end]
foreground = "#d9b911"
background = "#000000"

[cursor.style]
blinking = "On"

[mouse]
hide_when_typing = true
