# Number of lines in active history
HISTSIZE=512

# Number of lines in file history
HISTFILESIZE=1024

# Window title, prompt
PROMPT_COMMAND="source ~/.scripts/bash_prompt.sh"

# Functions
# Change location to a specific directory
cdoc()
{
	cd ~/Documents
}
cdwn()
{
	cd ~/Downloads
}
cprj()
{
	# If the directory doesn't exist, then creates it
	if [ -d ~/Documents/Projects ]
	then
		cd ~/Documents/Projects
	else
		mkdir -v ~/Documents/Projects
		cd ~/Documents/Projects
	fi
}
